"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Stacks Blockchain API
 * Welcome to the API reference overview for the [Stacks Blockchain API](https://docs.hiro.so/stacks-blockchain-api).  [Download Postman collection](https://hirosystems.github.io/stacks-blockchain-api/collection.json)
 *
 * The version of the OpenAPI document: STACKS_API_VERSION
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PoxSignerToJSON = exports.PoxSignerFromJSONTyped = exports.PoxSignerFromJSON = void 0;
function PoxSignerFromJSON(json) {
    return PoxSignerFromJSONTyped(json, false);
}
exports.PoxSignerFromJSON = PoxSignerFromJSON;
function PoxSignerFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'signing_key': json['signing_key'],
        'weight': json['weight'],
        'stacked_amount': json['stacked_amount'],
        'weight_percent': json['weight_percent'],
        'stacked_amount_percent': json['stacked_amount_percent'],
    };
}
exports.PoxSignerFromJSONTyped = PoxSignerFromJSONTyped;
function PoxSignerToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'signing_key': value.signing_key,
        'weight': value.weight,
        'stacked_amount': value.stacked_amount,
        'weight_percent': value.weight_percent,
        'stacked_amount_percent': value.stacked_amount_percent,
    };
}
exports.PoxSignerToJSON = PoxSignerToJSON;
//# sourceMappingURL=PoxSigner.js.map